### ISSUE TITLE
Dashboard with custom-ui generates HTTP-404 on mobile 

### ISSUE THREAD

**Issue by rsurgiewicz** [Mariusthvdb/custom-ui#10]
Hi there,
first of all big cudos for your work on the module!

I've included the module via lovelace resources as described in repo README.md
On my laptop it works as a charm but i got really confused it seems not to work on any mobile devices I have.

In HomeAssistant mobile app it causes some strange behaviour e.g dashboard is either not loaded or refreshing in loop.
Via Chrome browser on android I get 404 error when navigating to dashboard.

Is it expected behavior? 

my setup:
Frontend version: 20200811.0 - latest 
Home Assistant 0.115.0.dev20200813
CustomUI: JS 20200720 adapted for HA 110.+

lovelace.yaml
```
mode: yaml
resources: !include lovelace/resources.yaml
dashboards:
  lovelace-landpage:
    mode: yaml
    filename: ui-lovelace-landpage.yaml
    title: Start
    icon: mdi:account-group
    show_in_sidebar: true
    require_admin: false
```

lovelace/resources.yaml

```- url: /local/resources/custom-ui/custom-ui.js?v=20200528
  type: module
```

With resources:
**On laptop:**
![Screenshot_20200814_133234](https://user-images.githubusercontent.com/47541623/90245463-0235cc80-de33-11ea-9684-7af6cc74c911.png)

**On Android:**
![Screenshot_20200814_133821](https://user-images.githubusercontent.com/47541623/90245850-b7688480-de33-11ea-96d8-9cf57ce8ce9c.png)

**Without resources:**
On Android:
![image](https://user-images.githubusercontent.com/47541623/90245715-7f614180-de33-11ea-859a-28a964579b82.png)
