### ISSUE TITLE
icon_color, doesn't work for new badge in title, in section view.

### ISSUE THREAD

**Issue by WarC0zes** [Mariusthvdb/custom-ui#147]
**Describe the bug**
Hi,
Since update 2024.10.0, badges can be used in the title, in section view. But the icon color doesn't change. 
The icon does change though.

**Configuration in Yaml**
in customize.yaml
```
    binary_sensor.0x00158d0007ef4edc_contact:
      friendly_name: Porte Entrée
      templates:
        icon_color: >
          if (state == 'on') return '#ff0000';
          return '#00b300';
        icon: >
          if (state == 'on') return 'phu:panel-glass-door2-open';
          return 'phu:panel-glass-door2-close';
```

card code:
```
type: heading
heading: Salon
heading_style: title
badges:
  - type: entity
    show_state: true
    show_icon: true
    entity: binary_sensor.0x00158d0007ef4edc_contact
icon: mdi:sofa
```

**Inspector Logs**
No log

**Screenshots**
![image](https://github.com/user-attachments/assets/afb7dcad-6d11-4ae9-85ee-a2c1686bb30f)
![image](https://github.com/user-attachments/assets/460cbea5-a238-4a5e-9c46-43e68670a869)
