### ISSUE TITLE
Custom icons do not show up on iOS 10

### ISSUE THREAD

**Issue by jpirnie** [Mariusthvdb/custom-ui#27]
For some reason, if you set a custom icon using the code below, those icons won't show up on iOS 10 devices.  It does work on the computer and newer devices though.  It seems like anything inside the Templates: section is what it doesn't like.  I can set icons outside of that Templates: section and they do change on the iPad.  I tried putting the logic outside of the templates section but that didn't work either.

This is an example of what I have in my customize.yaml:

```yaml
switch.xmas_tree_big:
  templates:
    icon: >
      if (state === 'off') return 'mdi:pine-tree';
      if (state === 'on') return 'mdi:pine-tree';
    
    icon_color: >
      if (state === 'on') return 'rgb(255,0,0)';
```

This is what it looks like on the computer:
![8fdf144e6018a8309011664f346cdfc6ddc7c7b6](https://user-images.githubusercontent.com/33987478/102910339-41060f80-442f-11eb-8ca8-4e12d1465559.png)

This is what it looks like on an iOS 10 iPad 4:
![c180fa35d0552cb36082a8ed98c5092f48132b25_2_375x500](https://user-images.githubusercontent.com/33987478/102910363-4bc0a480-442f-11eb-9864-01a37760fa6f.jpeg)

**Comment by Mariusthvdb** [comment]
the top template is rather futile ;-)

why not try:

```
switch.xmas_tree_big:
    icon:  mdi:pine-tree
```
first? If that would work, you could make a better template,  using an 'if' and a guard (else), like in the many examples.

the color should work, (do note I always use '==' instead of '===', but that shouldn't be the cause here)

I've never run into an old iOS issue, and may not be able to mitigate that, especially if you are using the latest HA version? 

are you using the custom_ui of this repo, or the original, now deprecated version I mention in the readme?

**Comment by jpirnie** [comment]
> the top template is rather futile ;-)
> 
> why not try:
> 
> ```
> switch.xmas_tree_big:
>   icon: mdi:pine-tree
> ```
> 
> first? If that would work, you could make a better template, using an 'if' and a guard (else), like in the many examples.
> 
> the color should work, (do note I always use '==' instead of '===', but that shouldn't be the cause here)
> 
> I've never run into an old iOS issue, and may not be able to mitigate that, especially if you are using the latest HA version?
> 
> are you using the custom_ui of this repo, or the original, now deprecated version I mention in the readme?

That does indeed work.  But if I want to use an icon per state, how would I go about doing that?

**Comment by Mariusthvdb** [comment]
this works, but it also works without custom_ui.
for templates, and icon_color you need custom_ui.

in the examples file you can find many templates, based on state.

but they all require a correct install of custom_ui, hence my questions you havent answered yet. So back to basics for that.

**Comment by jpirnie** [comment]
I'm using 2020.12.1 HA, and I'm using the latest version from this Repro as I heard the other versions didn't work.  I can switch over to the == as well.

I installed custom_ui.js installed in this path: www/custom_ui/custom_ui.js.
Then in the Lovelace area of the UI, I have this defined as a resource: /local/custom_ui/custom_ui.js

I hope that answers questions about the install.  Let me know if there is something else I didn't provide.

I also changed the code to the following and it did not have any change in behavior.  It still shows the same default icon.

```yaml
switch.xmas_tree_big:
  templates:
    icon: >
      if (state == 'off') return 'mdi:lightbulb';
      else return 'mdi:lightbulb-on';
    
    icon_color: >
      if (state == 'on') return 'rgb(255,0,0)';
      else return 'rgb(255,255,255)';
```
