### ISSUE TITLE
confirm_controls seems not working

### ISSUE THREAD

**Issue by ed-holland** [Mariusthvdb/custom-ui#28]
I've installed custom-ui using HACS and it is working fine for the standard customizing changes like colors and icons.

When i try to add confirm_controls_show_lock or extra_badge etc, it does not seem to work.
Are these valid for your version of custom-ui?

**Inspect**
![image](https://user-images.githubusercontent.com/53995991/103137264-a8d68780-46c7-11eb-9727-f99743b5800a.png)

**Btw. the custom-ui is not showing up any more on /config/info**
![image](https://user-images.githubusercontent.com/53995991/103137272-c3106580-46c7-11eb-83ca-0899ab9f59dc.png)

**customizing:**
```
switch.sonoff_s55_4381:
  icon_color: gold
  show_last_changed: true
  confirm_controls_show_lock: true
  extra_badge:
    entity_id: sensor.sonoff_s55_4381_status
    attribute: LoadAvg
    unit: dBm
sensor.sonoff_s55_4381_status:
  icon_color: gold
  show_last_changed: true
  extra_data_template: "${attributes.LoadAvg}dBm"
```

**Resulting Entities Card**
![image](https://user-images.githubusercontent.com/53995991/103137303-184c7700-46c8-11eb-9e96-35b3e5f97393.png)
