### ISSUE TITLE
Customizing icon_color not working after browser refresh

### ISSUE THREAD

**Issue by ed-holland** [Mariusthvdb/custom-ui#29]
I'm using the HomeMatic integration and was trying to show correct color icons.
There is no reaction to the customizing implemented.
![image](https://user-images.githubusercontent.com/53995991/103139112-60c06080-46d9-11eb-88e1-e6c7c44858c5.png)

The entities do not seem to have a unique id ...
![image](https://user-images.githubusercontent.com/53995991/103139121-733a9a00-46d9-11eb-87f2-f961ab380486.png)

customizing:
```
sensor.hm_low_battery:
  templates:
    icon_color: if (state == 'O.K.') return 'green'; return 'orange';    
```

Any idea why this is not working?

**Comment by Mariusthvdb** [comment]
What is the state in developer-tools/states

**Comment by ed-holland** [comment]
yeah, using (comment was more textual)
```
  customize_domain: !include domain_customize.yaml
  customize: !include_dir_merge_named customize/
  customize_glob:
# All Entities - Hide Templates & Icon Color
    "*.*":
      hide_attributes:
        - templates
        - icon_color
```
Not so sure about the order to use on the three...

Checking it now a few hours later, it seems to be fine. Caching?

I noticed that when using the chrome-refresh button, all custom-ui changes disappear.

To answer your question:
![image](https://user-images.githubusercontent.com/53995991/103143254-a2213200-4712-11eb-9ecb-1dea71ddfa78.png)
