### ISSUE TITLE
Icon color

### ISSUE THREAD

**Issue by dowermyr** [Mariusthvdb/custom-ui#47]
Can't change some of my my cards ti different icon color.
This is my card, that is underneath a grid card:
` - type: button
        entity: binary_sensor.garageoppnare_channel_1_input
        name: Garageport
        show_name: true
        show_state: true
        show_icon: true
        tap_action:
          action: call-service
          service: script.oppna_stang_garageport
          confirmation:
            text: öppna / Stäng ?`

And this is the rows from the customize section;
`binary_sensor.garageoppnare_channel_1_input:
  templates:
    icon: >
      if (state === 'on') return 'mdi:garage-open-variant';
      return 'mdi:garage-variant';
    icon_color: >
      if (state ==='on') return 'red';
      if (state ==='off') return 'green';
      return 'green';`

The icon is changing but the colors is just the standard ones with yellow when on

**Comment by Mariusthvdb** [comment]
please format your code correctly so we can check for any edit flukes

using:
```
    - type: button
      entity: input_boolean.test
```

in the frontend view, and 

```
    input_boolean:
      templates:
          icon_color: >
            if (state === 'on') return 'var(--primary-color)';
            return 'steelblue';

```

works just fine

**Comment by dowermyr** [comment]
```
      - type: button
        entity: binary_sensor.garageoppnare_channel_1_input
        icon: mdi:garage-variant
        name: Garageport
        show_name: true
        show_state: true
        tap_action:
          action: call-service
          service: script.oppna_stang_garageport
          confirmation:
            text: öppna / Stäng ?
```

```
binary_sensor.garageoppnare_channel_1_input:
  templates:
    icon: >
      if (state === 'on') return 'mdi:garage-open-variant';
      return 'mdi:garage-variant';
    icon_color: >
      if (state ==='on') return 'red';
      return 'green';
```
Still not working.
All other cards I have works
