### ISSUE TITLE
Adding wildcard to sensor name causes error

### ISSUE THREAD

**Issue by ingo916** [Mariusthvdb/custom-ui#58]
If I add an * in the sensor name to include all devices similar in name I get an error when I check the config. If I add the sensors individually it works fine

### Entry in customize.yaml with wildcard
binary_sensor.lumi_lumi_sensor_wleak_aq1_*_ias_zone:
  templates:
    icon_color: >
          if (state === 'on') return 'red';
          return 'steelblue';

### Sensors listed individually works
binary_sensor.lumi_lumi_sensor_motion_aq2_c2abbc07_ias_zone:
  templates:
    icon_color: >
          if (state === 'on') return 'red';
          return 'steelblue';

binary_sensor.front_door_motion:
  templates:
    icon_color: >
          if (state === 'on') return 'red';
          return 'steelblue';

### Error checking config
extra keys not allowed @ data['customize']['binary_sensor.lumi_lumi_sensor_wleak_aq1_*_ias_zone']

![image](https://user-images.githubusercontent.com/41309095/164308072-ba614a90-94ad-41ff-9ec0-e163ac491850.png)

**Comment by Mariusthvdb** [comment]
please format your code correctly.

do read the examples, where it is stated that globs  need to go under
```
homeassistant:
  customize_glob:

```

**Comment by bratanon** [comment]
When using this:

```yaml
# configuration.yaml
input_boolean:
  test:
    name: Test boolean
    
template:
  - binary_sensor:
      - name: Test xx boolean
        state: "{{ states('input_boolean.test') }}"
      - name: Test yy boolean
        state: "{{ is_state('input_boolean.test', 'off') }}"
```
```yaml
# customize_glob.yaml
"binary_sensor.test_*_boolean":
  templates:
    icon: >
      return (state === 'on') ? 'mdi:test-tube' : 'mdi:test-tube-off';
    icon_color: >
      if (state === 'on') return 'red';
      return 'yellow';
```

It works as expected. 

As @Mariusthvdb said, please move your customization's to the correct config and try again. 

I will close this for now. Please feel free to re-poen it again if needed.
