### ISSUE TITLE
state_card not working (as in customizer)

### ISSUE THREAD

**Issue by inv1sible** [Mariusthvdb/custom-ui#9]
With the former [custom-ui](https://github.com/andrey-git/home-assistant-custom-ui/blob/master/docs/features.md#custom-controls)

and the following config:

```
customizer:
  custom_ui: local

frontend:
  extra_html_url:
    - /local/custom_ui/state-card-custom-ui.html
  extra_html_url_es5:
    - /local/custom_ui/state-card-custom-ui-es5.html
```
**Colors stopped working.** Can get them in `picture-elements-card` via style though:

```
[...]
style:
      '--paper-item-icon-color': '#FDD835'
[...]
```

**_Then I've found your rewriting of custom-ui and installed it quickly. THX. Gr8 work._**

But now I miss the buttons and all the other extras from the 'old' solution, see

With customizer:
![customizer](https://user-images.githubusercontent.com/13969630/89537614-e1012a80-d7f9-11ea-8531-3460b88eb8be.png)

With custom-ui:
![custom-ui](https://user-images.githubusercontent.com/13969630/89537824-245b9900-d7fa-11ea-8cda-177537cd3be0.png)

Any ideas? Thanks in advance....
